BeautySalon/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeautySalon.Data.Models;

namespace BeautySalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BeautysalonContext _context;

        public ClientsController(BeautysalonContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
              return _context.Clients != null ? 
                          View(await _context.Clients.ToListAsync()) :
                          Problem("Entity set 'BeautysalonContext.Clients'  is null.");
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,Name,FathersName,Phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Surname,Name,FathersName,Phone")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Clients == null)
            {
                return Problem("Entity set 'BeautysalonContext.Clients'  is null.");
            }
            var client = await _context.Clients.FindAsync(id);
            if (client != null)
            {
                _context.Clients.Remove(client);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(long id)
        {
          return (_context.Clients?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BeautySalon/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeautySalon.Data.Models;

namespace BeautySalon.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly BeautysalonContext _context;

        public EmployeesController(BeautysalonContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            var many = await _context.Employees.Include("EmployeesOnPositions.Pos").ToListAsync();
              return _context.Employees.Include("employeesonpositions") != null ? 
                          View(many) :
                          Problem("Entity set 'BeautysalonContext.Employees'  is null.");
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employees = _context.Employees.Include("EmployeesOnPositions.Pos").Where(emp=>emp.Id==id);
            var employee = employees.First();
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Surname,Name,FathersName,Phone")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'BeautysalonContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(long id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        
        public async Task<IActionResult> GetEmpsServices(long empid)
        {
            return View(await _context.Employees.Include("EmployeesOnPositions.Pos.Services")
                .Where(emp => emp.Id == empid).FirstOrDefaultAsync());
        }
    }
}

BeautySalon/Controllers/ViewModelsController.cs
using Microsoft.AspNetCore.Mvc;
using BeautySalon.Data.Models;
using Microsoft.EntityFrameworkCore;

using Controller = Microsoft.AspNetCore.Mvc.Controller;
using ModelState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateEntry;
using SelectList = Microsoft.AspNetCore.Mvc.Rendering.SelectList;

namespace BeautySalon.Controllers;

public class ViewModelsController : Controller
{
    private readonly BeautysalonContext _context;

    
    public ViewModelsController(BeautysalonContext context)
    {
        _context = context;
    }
    
    public IActionResult Create()
    {
        ViewData["Pos"] = new SelectList(_context.Positions, "Id", "Name");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Employee", "EmployeesOnPosition")] ViewModel model)
    {
        _context.Add(model.Employee);
        await _context.SaveChangesAsync();
        model.EmployeesOnPosition.Empid = model.Employee.Id;
        _context.Add(model.EmployeesOnPosition);
        await _context.SaveChangesAsync();
        return Redirect("/Employees");
    }

    public async Task<IActionResult> AddPos(long id)
    {
        var employees = _context.Employees.Include("EmployeesOnPositions.Pos").Where(emp=>emp.Id==id);
        var emp = await employees.FirstAsync();

        var takenPos = _context.EmployeesOnPositions.Where(emponpos=>emponpos.Empid==id);
        IEnumerable<Position> poses = _context.Positions;
        foreach (var pos in takenPos)
        {
            if (emp.EmployeesOnPositions.Contains(pos))
            {
                poses = poses.Where(p => p.Id != pos.Posid);
            }
        }
        ViewData["Pos"] = new SelectList(poses, "Id", "Name"); // await _context.Positions.Where(p=> _context.EmployeesOnPositions.FindAsync(p.Id) = false)
        var viewmodel = new ViewModel
        {
            Employee = emp
        };
        return View(viewmodel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddPos(long id, [Bind("Employee, EmployeesOnPosition")] ViewModel model)
    {
        model.EmployeesOnPosition.Empid = id;
        _context.Add(model.EmployeesOnPosition);
        await _context.SaveChangesAsync();
        return Redirect("/Employees/Edit/"+id);
    }
    
    [Route ("ViewModels/DelPos/{empid?}/{posid}")]
    public async Task<IActionResult> DelPos(long empid, long posid)
    {
        var employees = _context.Employees.Include("EmployeesOnPositions.Pos").Where(emp=>emp.Id==empid);
        var emp = await employees.FirstAsync();
        ViewData["Pos"] = new SelectList(_context.Positions, "Id", "Name");
        var viewmodel = new ViewModel
        {
            Employee = emp,
            EmployeesOnPosition = new EmployeesOnPosition {Empid = emp.Id, Posid = posid, Pos = await _context.Positions.FindAsync(posid)}
        };
        return View(viewmodel);
    }
    
    [HttpPost, ActionName("DelPos")]
    [ValidateAntiForgeryToken]
    [Route ("ViewModels/DelPos/{empid?}/{posid}")]
    public async Task<IActionResult> DelPosConfirmed(long empid, long posid)
    {
        var emponpos = await _context.EmployeesOnPositions.FindAsync(empid, posid);
        _context.EmployeesOnPositions.Remove(emponpos);
        await _context.SaveChangesAsync();
        return Redirect($"/ViewModels/AddPos/{empid}");
    }

    [Route ("ViewModels/ViewSchedule/{empid}")]
    public async Task<IActionResult> ViewSchedule(long empid, DateTime? date)
    {
        var viewmodel = new ViewModel
        {
            Employee = await _context.Employees
                .Include("Schedules.Serviceprovision.Cli")
                .Include("Schedules.Serviceprovision.Ser")
                .Where(emp => emp.Id == empid)
                .FirstOrDefaultAsync()
        };
        if (date.HasValue)
        {
            DateTime startDate = new DateTime(date.Value.Year, date.Value.Month, date.Value.Day, 0, 0, 0);
            DateTime endDate = new DateTime(date.Value.Year, date.Value.Month, date.Value.Day, 23, 59, 59);
            viewmodel.Employee.Schedules = viewmodel.Employee.Schedules.Where(s => s.Date > startDate && s.Date < endDate).ToList();
        }
        viewmodel.Employee.Schedules = viewmodel.Employee.Schedules.OrderBy(sch => sch.Date).ToList();
        return View(viewmodel);
    }
    
    [Route("ViewModels/ClientServices/{cliid?}")]
    public async Task<IActionResult> ClientServices(long cliid)
    {
        var viewmodel = new ViewModel
        {
            Client = await _context.Clients
                .Include("Serviceprovisions.Sch.Emp")
                .Include("Serviceprovisions.Ser")
                .Include("Serviceprovisions")
                .Where(cli => cli.Id == cliid)
                .FirstOrDefaultAsync()
        };
        return View(viewmodel);
    }

    [Route("ViewModels/SelectService/{cliid?}")]
    public async Task<IActionResult> SelectService(long cliid)
    {
        var services = await _context.Services.ToListAsync();
        var model = new ViewModel {Client = await _context.Clients.FindAsync(cliid)};
        ViewData["serid"] = new SelectList(services, "Id", "Name");
        return View(model);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("ViewModels/SelectService/{cliid?}")]
    public async Task<IActionResult> SelectService(long cliid, [Bind("Serviceprovision")] ViewModel model)
    {
        return Redirect($"/ViewModels/SelectTime/{cliid}/{model.Serviceprovision.Serid}");
    }

    [Route("ViewModels/SelectTime/{cliid?}/{serid?}")]
    public async Task<IActionResult> SelectTime(long cliid, long serid)
    {
        var service = await _context.Services.FindAsync(serid);
        // var position = await _context.Positions.FindAsync(service.Posid);
        var emponpos = await _context.EmployeesOnPositions.Where(ep=>ep.Posid == service.Posid).ToListAsync();
        var employees = new List<Employee>();
        foreach (var item in emponpos)
        {
            var emp = await _context.Employees.Include("EmployeesOnPositions")
                .Where(e => e.EmployeesOnPositions.Contains(item)).FirstOrDefaultAsync();
            employees.Add(emp);
        }
        // var employees = await _context.Employees.Where(e =>
            // e.EmployeesOnPositions.Contains()).ToListAsync();
    
    /*new KeyValuePair<string, long> {Key = "Empid", } <"Empid", e.Id> KeyValuePair<"Posid", service.Posid>*/
        // var schedules = await _context.Schedules.Where(sch=>sch.Emp)
        var schedules = await _context.Schedules.Include("Emp").Where(sch => employees.Contains(sch.Emp) && sch.Status=='-').ToListAsync();
        ViewData["schid"] = new SelectList(schedules, "Id", "Date");
        return View(new ViewModel {Client = await _context.Clients.FindAsync(cliid), Service = await _context.Services.FindAsync(serid)});
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("ViewModels/SelectTime/{cliid?}/{serid?}")]
    public async Task<IActionResult> SelectTime(long cliid, long serid, [Bind("Serviceprovision")] ViewModel model)
    {
        model.Serviceprovision.Cliid = cliid;
        model.Serviceprovision.Serid = serid;
        model.Schedule = await _context.Schedules.FindAsync(model.Serviceprovision.Schid);
        model.Schedule.Status = '+';
        _context.Update(model.Schedule);


        _context.Add(model.Serviceprovision);
        _context.SaveChanges();
        return Redirect($"/ViewModels/ClientServices/{cliid}");
    }
    // [Route("ViewModels/AddSerProv/{cliid?}/{serid}")]
    // 
    // public async Task<IActionResult> AddSerProv(long cliid, [Bind("")])
    // {
    //     
    //     return View();
    // }
    //
    // [HttpPost, ActionName("AddSerProv")]
    // [Route("ViewModels/AddSerProv/{cliid?}/{serid}")]
    // public async Task<IActionResult> AddSerProvCli(long cliid, long serid)
    // {
    //     var viewModels = new List<ViewModel>();
    //     var clients = await _context.Clients.ToListAsync();
    //     foreach (var client in clients)
    //     {
    //         viewModels.Add(new ViewModel {Client = client});
    //     }
    //
    //     return View(viewModels);
    // }
    
}

BeautySalon/Views/ViewModels/AddPos.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "Редактирование должностей";
}

<h1>Редактирование</h1>

<h4>Должности работника</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPos">
            <div class="form-group">
                <i>
                @Html.DisplayFor(modelItem => modelItem.Employee.Surname)
                @Html.DisplayFor(modelItem => modelItem.Employee.Name)
                @Html.DisplayFor(modelItem => modelItem.Employee.FathersName)
                </i>
            </div>
            <div class="form-group">
                @Html.DisplayFor(modelItem => modelItem.Employee.Phone)
            </div>
            <div class="form-group">
                @foreach (var itemPos in Model.Employee.EmployeesOnPositions)
                {
                    <li>
                        <a asp-action="DelPos" asp-route-empid="@itemPos.Empid" asp-route-posid="@itemPos.Posid">Удалить</a>
                        @Html.DisplayFor(modelItem => itemPos.Pos.Name)
                    </li>
                }
            </div>
            <div class="form-group">
                Должность
                <select asp-for="EmployeesOnPosition.Posid" class="form-control" asp-items="ViewBag.Pos"></select>
                <span asp-validation-for="EmployeesOnPosition.Posid" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Добавить должность" class="btn btn-primary"/>
            </div>
            
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Employees">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeautySalon/Views/ViewModels/ClientServices.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "Услуги клиента";
}

<h1>Услуги</h1>

<h4>Клиент:<i>
        @Html.DisplayFor(modelItem=> @Model.Client.Surname)
        @Html.DisplayFor(modelItem=> @Model.Client.Name)
        @Html.DisplayFor(modelItem=> @Model.Client.FathersName)
    </i> 
</h4>

<p>
    <a class="btn btn-primary" asp-action="SelectService" asp-route-cliid="@Model.Client.Id">Записать на услугу</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Услуга</th>
        <th>Мастер</th>
        <th>Номер телефона мастера</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in @Model.Client.Serviceprovisions)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Sch.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ser.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sch.Emp.Surname)
                @Html.DisplayFor(modelItem => item.Sch.Emp.Name)
                @Html.DisplayFor(modelItem => item.Sch.Emp.FathersName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sch.Emp.Phone)
            </td>
        </tr>
    }
    </tbody>
</table>

<div>
    <a asp-action="Index" asp-controller="Clients">Вернуться к списку</a>
</div>

BeautySalon/Views/ViewModels/Create.cshtml
@using BeautySalon.Data.Models
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "Создание";
}

<h1>Работник</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Фамилия
                <input asp-for="Employee.Surname" class="form-control" />
                <span asp-validation-for="Employee.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                Имя
                <input asp-for="Employee.Name" class="form-control" />
                <span asp-validation-for="Employee.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                Отчество
                <input asp-for="Employee.FathersName " class="form-control" />
                <span asp-validation-for="Employee.FathersName" class="text-danger"></span>
            </div>            
            <div class="form-group">
                Номер телефона
                <input asp-for="Employee.Phone" class="form-control" />
                <span asp-validation-for="Employee.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                Должность
                <select asp-for="EmployeesOnPosition.Posid" class="form-control" asp-items="ViewBag.Pos"></select>
                <span asp-validation-for="EmployeesOnPosition.Posid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Employees">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeautySalon/Views/ViewModels/DelPos.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "DelPos";
}
    <br/>

<h1>Уволить с должности</h1>
    <br/>

<h4>Вы уверены, что хотите удалить должность
    <i style="color: crimson">@Model.EmployeesOnPosition.Pos.Name </i><br/> работника <i style="color: crimson">@Model.Employee.Surname @Model.Employee.Name @Model.Employee.FathersName</i></h4>
    <br/>

<div>
    <br/>
    <form asp-action="DelPos">
        @* <input type="hidden" asp-    for="Id" /> *@
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="AddPos">Back to List</a>
    </form>
</div>

BeautySalon/Views/ViewModels/Index.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Employeeees</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Employee.Surname" class="control-label"></label>
                <input asp-for="Employee.Surname" class="form-control" />
                <span asp-validation-for="Employee.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Name" class="control-label"></label>
                <input asp-for="Employee.Name" class="form-control" />
                <span asp-validation-for="Employee.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.FathersName" class="control-label"></label>
                <input asp-for="Employee.FathersName" class="form-control" />
                <span asp-validation-for="Employee.FathersName" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Employee.Phone" class="control-label"></label>
                <input asp-for="Employee.Phone" class="form-control" />
                <span asp-validation-for="Employee.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeesOnPosition.Pos" class="control-label"></label>
                <input asp-for="EmployeesOnPosition.Pos" class="form-control" />
                <span asp-validation-for="EmployeesOnPosition.Pos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeautySalon/Views/ViewModels/SelectService.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "SelectService";
}
<h1>Запись на услугу</h1>
<hr />

<dl class="row">
    <dt class = "col-sm-2">
        Клиент
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(item=>@Model.Client.Surname)
        @Html.DisplayFor(item=>@Model.Client.Name)
        @Html.DisplayFor(item=>@Model.Client.FathersName)
    </dd>
    <dt class = "col-sm-2">
        Услуга
    </dt>
    
    <form asp-action="SelectService">
        <dd class = "col-sm-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <select asp-for="Serviceprovision.Serid" class="form-control" asp-items="ViewBag.Serid"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </dd>
    </form>
</dl>

<div>
    <a asp-action="Index" asp-controller="Clients">Вернуться к списку</a>
</div>

BeautySalon/Views/ViewModels/SelectTime.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "SelectTime";
}
<h1>Запись на услугу</h1>
<hr />
<dl class="row">
    <dt class = "col-sm-2">
        Клиент
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(item=>@Model.Client.Surname) @Html.DisplayFor(item=>@Model.Client.Name) @Html.DisplayFor(item=>@Model.Client.FathersName)
    </dd>
    <dt class = "col-sm-2">
        Услуга
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(item=>@Model.Service.Name)
    </dd>
    <dt class = "col-sm-2">
        Время
    </dt>
    <form asp-action="SelectTime">
        <dd class = "col-sm-12">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <select asp-for="Serviceprovision.Schid" class="form-control" asp-items="ViewBag.schid"></select>
        </div>
            <div class="form-group">
            <input type="submit" value="Создать" class="btn btn-primary"/>
        </div>
            </dd>

    </form>
</dl>

<div>
    <a asp-action="SelectService" asp-controller="ViewModels" asp-route-cliid="@Model.Client.Id">Вернуться к выбору услуги</a>
</div>

BeautySalon/Views/ViewModels/ViewSchedule.cshtml
@model BeautySalon.Data.Models.ViewModel

@{
    ViewData["Title"] = "ViewSchedule";
}

<h1>Расписание</h1>

<h4>Работник:<i>
        @Html.DisplayFor(modelItem=> @Model.Employee.Surname)
        @Html.DisplayFor(modelItem=> @Model.Employee.Name)
        @Html.DisplayFor(modelItem=> @Model.Employee.FathersName)
    </i> 
</h4>

<p>
     <a class="btn btn-primary" asp-action="Create" asp-controller="Schedules" asp-route-empid="@Model.Employee.Id">Создать новое</a>
 </p>

<form method="get">
    <div class="form-inline form-group">
        <label class="control-label">Дата: </label>
        <input type="datetime-local" name="date" class="form-control" />
        <input type="submit" value="Фильтр" class="btn btn-primary" />
    </div>
</form>

<table class="table">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Статус</th>
        <th>Клиента</th>
        <th>Номер телефона клиента</th>
        <th>Услуга</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in @Model.Employee.Schedules)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serviceprovision.Cli.Surname)
                @Html.DisplayFor(modelItem => item.Serviceprovision.Cli.Name)
                @Html.DisplayFor(modelItem => item.Serviceprovision.Cli.FathersName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serviceprovision.Cli.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serviceprovision.Ser.Name)
            </td>
            <td>
                @{
                    if (item.Status == '-')
                    {
                        <a asp-action="Delete" asp-controller="Schedules" asp-route-id="@item.Id" class="btn btn-danger">Удалить</a>
                    }
                }
            </td>
        </tr>
        
    }
    </tbody>
</table>

<a asp-action="Index" asp-controller="Employees">Вернуться к списку работников</a>